version: '3.9'

services:

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: servicetest
      MONGO_INITDB_ROOT_PASSWORD: servicetest
      MONGO_INITDB_DATABASE: servicetest
    ports:
      - "10000:27017"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://servicetest:servicetest@database:27017

  redis_cache:
    image: redis:latest
    command: redis-server --maxmemory 100mb  --maxmemory-policy allkeys-lfu --appendonly no --stop-writes-on-bgsave-error no --lfu-log-factor 10 --lfu-decay-time 1
    ports:
      - "10001:6379"
